### ISSUE TITLE
Buffering lenght

### ISSUE THREAD

**Issue by kurdd** [clappr/clappr-rtmp-plugin#31]
Hi guys, thank you for nice plugin for nice player. Could you please explain how could I set buffering size or rtmp stream. 

Thank you

**Comment by gfronza** [comment]
Hi @kurdd. Last week we pushed a new version of the plugin. Now you can set the bufferTime on the options:

```javascript
var player = new Clappr.Player({
    source: "rtmp://source_here",
    parentId: "#player-wrapper",
    plugins: {'playback': [RTMP]},
    rtmpConfig: {
        swfPath: 'dist/assets/RTMP.swf',
        scaling:'stretch',
        playbackType: 'live',
        bufferTime: 1,
        startLevel: 0
    },
});
```

**Comment by galedric** [comment]
The default value is chosen if bufferTime *evaluates* to false (because of the `||` operator).
As a result, it is not possible to set bufferTime to 0, disabling buffering entirely.

https://github.com/clappr/clappr-rtmp-plugin/blob/master/src/main.js#L34

I believe `=== undefined` would be a better check here.

This is required in the case the application focuses on no-delay streaming. Even a buffering of 0.1 secs will accumulate latency in the long run if re-buffering is required. A buffering of 0 will always be as live as possible.

**Comment by gfronza** [comment]
@galedric I used the || operator on purpose there, because my experience with bufferTime 0 is that it brings a lot of side effects. But I agree that this should be the programmers' responsibility, so will change this behaviour. Thanks for pointing that out.

**Comment by gfronza** [comment]
@galedric https://github.com/clappr/clappr-rtmp-plugin/pull/35 will fix it.
